apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: hello-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-python
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      securityContext:
        #runAsNonRoot: true
        #runAsUser: 65534
        #fsGroup: 65534
      containers:
        - name: mentimeter-back
          image: library/python-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
                path: /
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            readinessProbe:
            httpGet:
                path: /
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: "150m"
              memory: "512Mi"
            requests:
              cpu: "150m"
              memory: "512Mi"